name: Build & Push Images
on:
  push: { branches: [main] }
permissions:
  contents: read
  packages: write
env:
  REGISTRY: ghcr.io
  ORG: Dkid713
jobs:
  build:
    runs-on: ubuntu-latest
    strategy: { matrix: { svc: [compression, avi-runtime, aap-gateway] } }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./services/${{ matrix.svc }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.ORG }}/${{ matrix.svc }}:latest
            ${{ env.REGISTRY }}/${{ env.ORG }}/${{ matrix.svc }}:${{ github.sha }}
